[env:cyd]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
; 日本語フォントでフラッシュを使うので大きめのパーティションを使う
board_build.partitions = huge_app.csv
lib_deps =
    lovyan03/LovyanGFX@^1.1.16
    bblanchon/ArduinoJson@^7.0.0
